# Generated by Django 4.2 on 2023-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='emails',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.RemoveField(
            model_name='room',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='email2',
        ),
    ]
