# Generated by Django 4.2 on 2023-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('O', 'Offer'), ('W', 'Wish')], max_length=1)),
                ('condition', models.CharField(choices=[('N', 'New'), ('G', 'Good '), ('E', 'Excellent'), ('S', 'Satisfactory')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cover', models.ImageField(blank=True, default='book-cover/no_cover.png', null=True, upload_to='book-cover/')),
            ],
        ),
    ]
