# Generated by Django 4.2 on 2023-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('G', 'Good '), ('E', 'Excellent'), ('S', 'Satisfactory')], max_length=1),
        ),
    ]
